version: '3'

services:
  wordpress:
    build: requirements/wordpress
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - wp:/var/www/html/wordpress
      - adm:/var/www/html/adminer
    networks:
      - app
    depends_on:
      - redis
    container_name: wordpress
    env_file:
      - .env

  nginx:
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html/wordpress
      - adm:/var/www/html/adminer
    depends_on:
      - wordpress
    networks:
      - app
    container_name: nginx

  mariadb:
    build: requirements/mariadb
    restart: always
    env_file: 
      .env
    ports:
      - "3306:3306"
    volumes:
      - data-db:/var/lib/mysql
    networks:
      - app
    container_name: mariadb

  redis:
    build: requirements/redis
    restart: always
    depends_on:
      - mariadb
    networks:
      - app
    container_name: redis
    ports:
      - "6379:6379"

  ftp:
    build: requirements/ftp
    # restart: always
    networks:
      - app
    container_name: ftp
    ports:
      - "21:21"
      - "20:20"
    volumes:
      - wp:/var/ftp

  adminer:
    build: requirements/adminer
    # restart: always
    ports:
      - "4443:4443"
    volumes:
      - adm:/var/www/html/adminer
    networks:
      - app
    depends_on:
      - redis
    container_name: adminer
    env_file:
      - .env
    
volumes:
  data-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/namina/data/db-data
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/namina/data/wp

  adm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/namina/data/adm

networks:
  app: 
    driver: bridge


      # change to /home/namina/data/db:/var/lib/mysql
  # nginx:
  #   build: requirements/nginx
