version: '3'

services:
  wordpress:
    build: requirements/wordpress
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - app
    depends_on:
      - mariadb
    container_name: wordpress
    env_file:
      - .env

  nginx:
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
      - "8888:8888"
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - app
    container_name: nginx

  mariadb:
    build: requirements/mariadb
    restart: always
    env_file: 
      .env
    ports:
      - "3306:3306"
    volumes:
      - data-db:/var/lib/mysql
    networks:
      - app
    container_name: mariadb

volumes:
  data-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/namina/db-data
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/namina/wp


networks:
  app: 
    driver: bridge


      # change to /home/namina/data/db:/var/lib/mysql
  # nginx:
  #   build: requirements/nginx
